--  CREATE & USE DATABASE COLLAGEDB
CREATE DATABASE IF NOT EXISTS COLLAGEDB;
USE COLLAGEDB;

-- CREATE DEPT TABLE

CREATE TABLE DEPERTMENT (
ID INT PRIMARY KEY,
NAME VARCHAR(50) NOT NULL
);

-- CREATE STUDENT TABLE
CREATE TABLE STUDENT (
STUDENT_ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
AGE INT CHECK(AGE>=18),
COUNTRY VARCHAR(50) DEFAULT 'INDIA',
DEPT_ID INT,
FOREIGN KEY (DEPT_ID) REFERENCES DEPERTMENT (ID)
);

-- INSERT DATA
INSERT INTO DEPERTMENT (ID, NAME) VALUES 
(1, 'ECE'), (2, 'CSE'), (3, 'EE');
INSERT INTO STUDENT (NAME, AGE, COUNTRY, DEPT_ID) VALUES 
('Rahul', 20, 'INDIA', 1),
('Priya', 21, 'INDIA', 2),
('Amit', 19, 'INDIA', 3),
('Sneha', 22, 'INDIA', 1),
('Arjun', 20, 'INDIA', 2),
('Ananya', 19, 'INDIA', 3),
('Rohan', 23, 'INDIA', 1),
('Kavya', 21, 'INDIA', 2),
('Vikram', 22, 'INDIA', 3),
('Neha', 20, 'INDIA', 1);

-- DEFAULT INDIA

INSERT INTO STUDENT (NAME, AGE, DEPT_ID) VALUES 
('SURAJIT', 21, 1);

-- VIEW ALL DATA

SELECT * FROM STUDENT;
SELECT * FROM DEPERTMENT;

SELECT NAME FROM STUDENT;
SELECT NAME FROM STUDENT WHERE DEPT_ID = 1;

